[package]
name = "strs"
version = "0.1.0"
authors = ["Casey Rodarmor <casey@rodarmor.com>"]
edition = "2018"

[dependencies]
structopt = "^0.2.15" # 0.2.16 OK (0.3.0 NOT OK)
# fooopt = "^1.0.0" # 1.1.0 OK (2.0.0 NOT OK)
